### ISSUE TITLE
Is there any way to retrieve the offset at which a file starts?

### ISSUE THREAD

**Issue by xplshn** [maja42/ember#5]
Hi, awesome project, I've been trying to use it to retrieve the offset of an appdir.dwfs embedded into my `pelf` runtime, basically, I need to retrieve the offset so that I can tell the `dwarfs` command where the archive starts, I need this to be able to mount the archive without saving it to a file.
Thanks!

note: dwarfs is an archival format that can be mounted, just like `squashfs`.

**Comment by xplshn** [comment]
PR: https://github.com/maja42/ember/pull/6
:)

**Comment by maja42** [comment]
Are you forwarding the offset to an external application/command? I would have assumed that the io.Reader is sufficient.

Adding this feature would prevent future changes how the data is appended (compression, encryption, ...). But since the library is stable and I don't plan on changing the internals, exposing the offset seems doable.

**Comment by xplshn** [comment]
> Are you forwarding the offset to an external application/command? Otherwise I would have assumed that the io.Reader is sufficient.

Yeah, I need to pass the offset to the `dwarfs` command, which mounts the `.dwfs` archive

**Comment by maja42** [comment]
@xplshn Is this feature no longer needed for your use case?

**Comment by xplshn** [comment]
> @xplshn Is this feature no longer needed for your use case?

It is, that's why I came back to see if it was merged

**Comment by maja42** [comment]
Now included in v1.3.0
